### ISSUE TITLE
v1.0 checklist

### ISSUE THREAD

**Issue by hwchen** [tesseract-olap/tesseract#2]
## Features checklist
- [ ] mondrian rest-like interface
  - [ ] filter and order on dimensions and measures  
  - [x] output csv and jsonrecords
- [x] annotations
- [ ] support non-aggregated cube (through separate api)
- [ ] built-in aggregations
  - [ ] sum, median, avg, count
  - [ ] moe, growth, rca
- [ ] built-in selection of measures depending on hierarchy (currently supported, but no default hierarchy).
- [ ] some kind of arbitrary calculation

## Other features, may be 1.0 or later
- [ ] multiple db
- [ ] retrieve schema from db

**Comment by hwchen** [comment]
Yup, definitely! There will be something like an `Aggregation` trait or
enum so that an aggregation can be defined with reference to an iterator or
array.

**Comment by MarcioPorto** [comment]
@hwchen Perhaps we should update the status of the features in this issue, or close it if everything has already been implemented.

**Comment by hwchen** [comment]
I'm going to close this, as the roadmap is a little different now.
